[package]
name = "rey-v0"
version = "0.1.0"
edition = "2021"

description = "Rey v0 reference interpreter"
license = "MIT"
authors = ["Misbah Khursheed <m.misbahkhursheed@gmail.com>"]

[dependencies]
